apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit
  template:
    metadata:
      labels:
        app: audit
    spec:
      containers:
        - name: audit
          image: eliyashlomo7/audit-app:latest  
          env:
            - name: DATABASE_URL
              value: postgresql://user:password@audit-postgres:5432/gardening_audit
          ports:
            - containerPort: 8000
