apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: eliyashlomo7/notification-app:latest  
          env:
            - name: DATABASE_URL
              value: postgresql://user:password@notification-postgres:5432/gardening_notification
          ports:
            - containerPort: 8000
