apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app: notification
spec:
  type: ClusterIP
  selector:
    app: notification
  ports:
    - name: http      
      port: 8000
      targetPort: 8000
