"""added client_create column, for using the repots.py

Revision ID: b770e7816f7a
Revises: bc35f5dd3791
Create Date: 2025-07-07 11:11:37.966197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b770e7816f7a'
down_revision: Union[str, Sequence[str], None] = 'bc35f5dd3791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'created_at')
    # ### end Alembic commands ###
