apiVersion: v1
kind: Service
metadata:
  name: users
  labels:
    app: users
spec:
  type: ClusterIP
  selector:
    app: users
  ports:
    - name: http      
      port: 8000
      targetPort: 8000
