apiVersion: v1
kind: Service
metadata:
  name: appointments
  labels:
    app: appointments
spec:
  type: ClusterIP
  selector:
    app: appointments
  ports:
    - name: http      
      port: 8000
      targetPort: 8000
