apiVersion: v1
kind: Service
metadata:
  name: clients
  labels:
    app: clients
spec:
  type: ClusterIP
  selector:
    app: clients
  ports:
    - name: http      
      port: 8000
      targetPort: 8000
