apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-postgres
spec:
  selector:
    matchLabels:
      app: inventory-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: inventory-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: gardening_inventory
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          emptyDir: {}
