apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  type: ClusterIP
  selector:
    app: inventory
  ports:
    - name: http      
      port: 8000
      targetPort: 8000
